### ISSUE TITLE
Error when trying to salvage machines

### ISSUE THREAD

**Issue by ThatCat287** [Jackarunda/gmod#128]
I have tested this with no addons except jmod, and it still creates the error. Whenever I try to salvage a complex machine, it does not allow me to, and it creates this error: [JMod] lua/weapons/wep_jack_gmod_eztoolbox.lua:507: attempt to index field 'Config' (a nil value)
    1. unknown - lua/weapons/wep_jack_gmod_eztoolbox.lua:507

**Comment by AdventureBootCoder** [comment]
Fixed in the current Github version
