### ISSUE TITLE
General bugs

### ISSUE THREAD

**Issue by wolfestridershooter** [Jackarunda/gmod#189]
Here's three general bugs I could find

1.
I'm not sure if this is a bug or not but if you tap a resource extractor (Pumpjack and / or Auger Drill) with a battery it resets it's progress on it's current progress of extracting the resource it was extracting.

2.
Sometimes a resource extractor will stop making sound while pumping / drilling (Pumpjack and / or Auger Drill)

3.
The Auger Drill's drill casing is shown untextured at the top of the model sometimes:
![image](https://user-images.githubusercontent.com/47306808/226796277-6e73e464-9873-4995-bcb7-79cfb3bfe606.png)

**Comment by AdventureBootCoder** [comment]
1. I've fixed, it will be deployed ASAP
2. I'm pretty sure I fixed it, but I'll have to double check, thanks
3. That's on me, I didn't think it'd go up that far.

Thanks for the report. 👍

**Comment by wolfestridershooter** [comment]
np, I also have three more bugs to report:

4.
If you spawn a Solar Panel and then delete it and wait ten minutes you'll get this error:

[JMod] lua/entities/ent_jack_gmod_ezsolargenerator.lua:128: attempt to call method 'TurnOff' (a nil value)
  1. unknown - lua/entities/ent_jack_gmod_ezsolargenerator.lua:128

Timer Failed! [SolarAutoShutOff5][@lua/entities/ent_jack_gmod_ezsolargenerator.lua (line 128)]

5.
A couple of the bomb's hitboxes are very inaccurate, you can just flip some of them upside down and make them turn black, make their fins and / or warheads go straight through the ground, and stand them up in impossibly precarious positions. These very inaccurate hitboxes also make their shadows look like rectangles.
Here's the offending bombs:
ent_jack_gmod_ezbigbomb
ent_jack_gmod_ezbomb
ent_jack_gmod_ezmoab
ent_jack_gmod_eznuke
ent_jack_gmod_ezsmallbomb
ent_jack_gmod_eznuke_big

Here's a screenshot so you can see what I'm talking about:
![image](https://user-images.githubusercontent.com/47306808/226865338-88963125-b0e8-426c-868f-ef9118729f15.png)


6.
The engine impact / scrape / footstep sounds for a lot of items are completely mixed up, if you want me to list all of the offending entities and what their sounds likely should be let me know but I'll just name two that are the worst offenders:

Cloth Roll Resource sounding like metal when you scrape it along the floor or step / jump on it.
Water Drum sounding like weapons when you drop it lightly on the floor.

7.
When you pick up Fissile Material by pressing the use key it rotates itself so the text is backwards from you point of view, no other resource does this.

**Comment by AdventureBootCoder** [comment]
4. Fixed on the GH version
5. I wasn't around when they made those, but I imagine the original phys objects had some undesired properties so they were replaced by regular phys-plates.
6. Since a lot of the entities use custom collision methods, some of the sound effects may have been forgotten to be changed or inherited a sound effect from their base ent. I've fixed a few that we know and I'll get to the water drum and cloth roll soon.
7. Oh, I'll definitely look into that, thanks. 👍

**Comment by wolfestridershooter** [comment]
5. I'd say the worst one is ent_jack_gmod_ezsmallbomb, I'd say that's when you get into gameplay issues because of the fact that you can load them into a way smaller space then you normally could (I'm also a sucker for accurate hitboxes so I'm a bit biased though lol)
