### ISSUE TITLE
Dedicated server error

### ISSUE THREAD

**Issue by Smearfo** [Jackarunda/gmod#207]
When running on a dedicated server, jmod spams the console with

[JMod] lua/jmod/sh_equippables.lua:151: attempt to call field 'Iterator' (a nil value)
  1. fn - lua/jmod/sh_equippables.lua:151
   2. unknown - lua/ulib/shared/hook.lua:109

**Comment by AdventureBootCoder** [comment]
Update your server to latest GMod, it's a new function that got added
