### ISSUE TITLE
Error Thrown When Eating Nutrients

### ISSUE THREAD

**Issue by Xorgadget** [Jackarunda/gmod#53]
Model missing: models/props/cs_office/Water_bottle.mdl
ERROR!: Can't create physics object for models/props/cs_office/Water_bottle.mdl

[gmod] addons/gmod/lua/entities/ent_jack_gmod_eznutrients.lua:37: Tried to use a NULL physics object!
  1. SetVelocity - [C]:-1
   2. FlingProp - addons/gmod/lua/entities/ent_jack_gmod_eznutrients.lua:37
    3. UseEffect - addons/gmod/lua/entities/ent_jack_gmod_eznutrients.lua:43
     4. AltUse - addons/gmod/lua/entities/ent_jack_gmod_eznutrients.lua:62
      5. unknown - addons/gmod/lua/entities/ent_jack_gmod_ezresource.lua:95

Possible Missing Prop

**Comment by Xorgadget** [comment]
Could Be Fixed By using IsValid()

**Comment by Xorgadget** [comment]
Could Not Reproduce

**Comment by klen-list** [comment]
Disable css content and u can.
Maybe already need to write in the addon description that need have this content installed?

**Comment by klen-list** [comment]
![UNKVp6R5EE](https://user-images.githubusercontent.com/49125075/122088011-08f3ee00-ce0e-11eb-9d3e-473be7692a87.png)
