### ISSUE TITLE
Manual Weapon Pickup conflicts with JMOD guns.

### ISSUE THREAD

**Issue by XxFaZeDerpsxX** [Jackarunda/gmod#72]
If the Manual Weapon Pickup mod from the workshop is enabled at the same time as JMOD, attempting to pick up a JMOD weapon will result in a script error, plus, the gun is added to your inventory, but is not removed from the ground, allowing you to duplicate the guns infinitely.

**Comment by AdventureBootCoder** [comment]
Are you picking up gun entities or gun sweps?
