### ISSUE TITLE
fix viewmodel angles

### ISSUE THREAD

**Issue by MonkaSC** [Jackarunda/gmod#78]
circle is center of screen
instead of this
![image](https://user-images.githubusercontent.com/54508597/113606778-74535f80-9616-11eb-80f5-dcdc9ca18e0e.png)
![image](https://user-images.githubusercontent.com/54508597/113606972-b086c000-9616-11eb-8897-0ca417a87bae.png)

do this
![image](https://user-images.githubusercontent.com/54508597/113606875-90570100-9616-11eb-8a5d-557fc845d5ea.png)
![image](https://user-images.githubusercontent.com/54508597/113607025-bf6d7280-9616-11eb-8e5a-fb346cd22257.png)
(please)

**Comment by Wgairborne** [comment]
remembered this was a feature put in by jack, just cope I guess :trollface:

**Comment by MonkaSC** [comment]
thats why your guns dead asf hoe ass nigga

**Comment by Wgairborne** [comment]
shrimply seethe and cope
