### ISSUE TITLE
Wiki page "Configuring JMod" appears to be out of date

### ISSUE THREAD

**Issue by OctothorpeObelus** [Jackarunda/gmod#87]
For the Building Functions overview I noticed that the examples shown no longer worked. After an hour and a half of debugging I got it to work with the jmod_lua_config.lua in garrysmod/lua/autorun.

Here's what I did to fix it for me:
![image](https://user-images.githubusercontent.com/10675391/125243250-d5489e80-e2bb-11eb-8411-be753b03c11a.png)
- The underlined portion was replaced with `JMOD_LUA_CONFIG` 
- `JMod = JMod or {}` was added on line 3 to avoid nil reference errors
- `Ent.Owner = playa` was replaced with `Ent:SetCreator(playa)` to fix the no owner issue for prop protection addons

Complete code for a fixed example of prop_physics:
```lua
-- Autorun file
AddCSLuaFile()

JMod = JMod or {}
JMod.LuaConfig = JMOD_LUA_CONFIG or {}
JMod.LuaConfig.BuildFuncs = JMod.LuaConfig.BuildFuncs or {}

JMod.LuaConfig.BuildFuncs["spawnMyThing"] = function(playa, position, angles)
    local Ent = ents.Create("prop_physics")
    Ent:SetModel("models/MyThing.mdl")
    Ent:SetPos(position)
    Ent:SetAngles(angles)
    Ent:SetCreator(playa)
    Ent:Spawn()
end
```

With all this done there were no seen conflicts or errors and everything appeared to function correctly.

The section where the custom building prop is added to the config is also mismatched with the function name, and should match what was put in `JMod.LuaConfig.BuildFuncs["spawnMyThing"] = function(playa, position, angles)`

```json
"My Cool Thing": [
	"FUNC spawnMyThing",
	{
                 "parts": 20.0
	},
	1.0,
	"Other"
]
```

It should also be noted on the wiki that the float following the material requirements table is the amount of entities spawned when air dropped (from what I could gather, but I'm sure I'm incorrect on this) and that the string on the line after is the category it is put in within the build menu, which can be anything.

**Comment by TheOnly8Z** [comment]
updated
